package com.parth.portfolio.portfolio.media.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;

@Service
public class LocalFileStorageService {

    public record StoredFile(
            String originalFileName,
            String storedFileName,
            String type,
            String mimeType,
            long size,
            Path path
    ) {
    }

    private static final Set<String> ALLOWED_IMAGE_TYPES = Set.of(
            "image/jpeg",
            "image/png",
            "image/webp"
    );

    private static final Set<String> ALLOWED_PDF_TYPES = Set.of(
            "application/pdf"
    );

    private static final long MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB

    private final Path storageDirectory;

    public LocalFileStorageService(
            @Value("${app.storage.local-dir:./uploads}") String storageDirectory) {

        this.storageDirectory = Path.of(storageDirectory)
                .toAbsolutePath()
                .normalize();

        try {
            Files.createDirectories(this.storageDirectory);
        } catch (IOException e) {
            throw new IllegalStateException(
                    "Unable to initialize file storage directory",
                    e
            );
        }
    }

    /**
     * Stores a validated image or PDF.
     *
     * IMPORTANT:
     * The original filename is never used as the stored filename.
     */
    public StoredFile  store(MultipartFile file) {

        validateBasicFileProperties(file);

        String contentType = normalizeContentType(file.getContentType());

        if (ALLOWED_IMAGE_TYPES.contains(contentType)) {
            validateImage(file, contentType);
        } else if (ALLOWED_PDF_TYPES.contains(contentType)) {
            validatePdf(file);
        } else {
            throw new IllegalArgumentException(
                    "Unsupported file type"
            );
        }

        String extension = determineExtension(contentType);

        String storedName =
                UUID.randomUUID() + extension;

        Path target = storageDirectory
                .resolve(storedName)
                .normalize();

        /*
         * Defense in depth against path traversal.
         *
         * Because storedName is generated by us, traversal is already
         * prevented, but this check should remain.
         */
        if (!target.getParent().equals(storageDirectory)) {
            throw new SecurityException(
                    "Invalid storage path"
            );
        }

        try (InputStream inputStream = file.getInputStream()) {

            Files.copy(
                    inputStream,
                    target,
                    StandardCopyOption.REPLACE_EXISTING
            );

       return new StoredFile(
            file.getOriginalFilename(),
            storedName,
            determineExtension(contentType),
            contentType,
            file.getSize(),
            target
        );

        } catch (IOException e) {

            /*
             * Do not leave a partially-written file behind.
             */
            try {
                Files.deleteIfExists(target);
            } catch (IOException ignored) {
                // Best effort cleanup.
            }

            throw new IllegalStateException(
                    "Failed to store uploaded file",
                    e
            );
        }
    }

    /**
     * Performs basic multipart validation.
     */
    private void validateBasicFileProperties(MultipartFile file) {

        if (file == null || file.isEmpty()) {
            throw new IllegalArgumentException(
                    "File must not be empty"
            );
        }

        if (file.getSize() > MAX_FILE_SIZE) {
            throw new IllegalArgumentException(
                    "File exceeds the maximum allowed size of 10 MB"
            );
        }

        /*
         * MultipartFile#getSize() is checked before reading the file.
         *
         * The server/container should ALSO enforce its multipart
         * request limits through application configuration.
         */
        if (file.getSize() <= 0) {
            throw new IllegalArgumentException(
                    "File must contain data"
            );
        }
    }

    /**
     * Validates an image using actual image decoding.
     *
     * Content-Type alone is NOT trusted.
     */
    private void validateImage(
            MultipartFile file,
            String declaredContentType) {

        try (InputStream inputStream = file.getInputStream()) {

            BufferedImage image = ImageIO.read(inputStream);

            /*
             * ImageIO.read() returns null when the input cannot be
             * decoded as a supported image.
             */
            if (image == null) {
                throw new IllegalArgumentException(
                        "Uploaded file is not a valid image"
                );
            }

            /*
             * Ensure dimensions are sensible.
             *
             * This protects against extremely large decompressed
             * images causing excessive memory consumption.
             */
            if (image.getWidth() <= 0 ||
                    image.getHeight() <= 0) {

                throw new IllegalArgumentException(
                        "Invalid image dimensions"
                );
            }

            /*
             * Prevent decompression bombs / unreasonable dimensions.
             */
            long pixels =
                    (long) image.getWidth() *
                    (long) image.getHeight();

            long maxPixels = 25_000_000L;

            if (pixels > maxPixels) {
                throw new IllegalArgumentException(
                        "Image dimensions are too large"
                );
            }

            /*
             * Verify that the actual image format matches the
             * declared Content-Type.
             */
            String detectedFormat = detectImageFormat(file);

            if (!isMatchingImageType(
                    declaredContentType,
                    detectedFormat)) {

                throw new IllegalArgumentException(
                        "File content does not match its declared type"
                );
            }

        } catch (IOException e) {

            throw new IllegalArgumentException(
                    "Unable to inspect uploaded image",
                    e
            );
        }
    }

    /**
     * Detects the actual image format using ImageIO readers.
     */
    private String detectImageFormat(MultipartFile file)
            throws IOException {

        try (InputStream inputStream = file.getInputStream()) {

            var imageInputStream =
                    ImageIO.createImageInputStream(inputStream);

            if (imageInputStream == null) {
                throw new IllegalArgumentException(
                        "Unable to inspect image format"
                );
            }

            try (imageInputStream) {

                var readers =
                        ImageIO.getImageReaders(imageInputStream);

                if (!readers.hasNext()) {
                    throw new IllegalArgumentException(
                            "Unknown or unsupported image format"
                    );
                }

                var reader = readers.next();

                try {
                    return reader.getFormatName()
                            .toLowerCase(Locale.ROOT);
                } finally {
                    reader.dispose();
                }
            }
        }
    }

    /**
     * Ensures the detected image format agrees with the declared MIME.
     */
    private boolean isMatchingImageType(
            String contentType,
            String detectedFormat) {

        return switch (contentType) {

            case "image/jpeg" ->
                    detectedFormat.equals("jpeg")
                            || detectedFormat.equals("jpg");

            case "image/png" ->
                    detectedFormat.equals("png");

            case "image/webp" ->
                    detectedFormat.equals("webp");

            default ->
                    false;
        };
    }

    /**
     * Validates the PDF magic/signature.
     *
     * A PDF must begin with %PDF-.
     */
    private void validatePdf(MultipartFile file) {

        byte[] header = new byte[5];

        try (InputStream inputStream = file.getInputStream()) {

            int bytesRead = inputStream.read(header);

            if (bytesRead != 5) {
                throw new IllegalArgumentException(
                        "Invalid PDF file"
                );
            }

            if (header[0] != '%' ||
                    header[1] != 'P' ||
                    header[2] != 'D' ||
                    header[3] != 'F' ||
                    header[4] != '-') {

                throw new IllegalArgumentException(
                        "Uploaded file is not a valid PDF"
                );
            }

        } catch (IOException e) {

            throw new IllegalArgumentException(
                    "Unable to inspect uploaded PDF",
                    e
            );
        }
    }

    /**
     * Normalizes the client-provided MIME value.
     */
    private String normalizeContentType(String contentType) {

        if (contentType == null) {
            return "";
        }

        return contentType
                .trim()
                .toLowerCase(Locale.ROOT);
    }

    /**
     * Determines the extension exclusively from our validated
     * Content-Type, never from the client filename.
     */
    private String determineExtension(String contentType) {

        return switch (contentType) {

            case "image/jpeg" -> ".jpg";
            case "image/png" -> ".png";
            case "image/webp" -> ".webp";
            case "application/pdf" -> ".pdf";

            default ->
                    throw new IllegalArgumentException(
                            "Unsupported file type"
                    );
        };
    }

    /**
     * Resolves a stored file safely.
     */
    public Path resolve(String storedName) {

        if (storedName == null || storedName.isBlank()) {
            throw new IllegalArgumentException(
                    "Invalid stored filename"
            );
        }

        /*
         * Stored names are generated by this service.
         * Reject anything that does not look like one of our names.
         */
        if (!storedName.matches(
                "^[a-fA-F0-9-]{36}\\.(jpg|png|webp|pdf)$")) {

            throw new IllegalArgumentException(
                    "Invalid stored filename"
            );
        }

        Path resolved = storageDirectory
                .resolve(storedName)
                .normalize();

        if (!resolved.getParent().equals(storageDirectory)) {
            throw new SecurityException(
                    "Invalid file path"
            );
        }

        return resolved;
    }

    /**
     * Deletes a stored file safely.
     */
    public void delete(String storedName) {

        Path file = resolve(storedName);

        try {
            Files.deleteIfExists(file);
        } catch (IOException e) {
            throw new IllegalStateException(
                    "Failed to delete stored file",
                    e
            );
        }
    }

    /**
     * Checks whether a stored file exists.
     */
    public boolean exists(String storedName) {
        return Files.isRegularFile(resolve(storedName));
    }
}